=== jdolinski1/reacting-squirrel-fix/schemas/rsconfig.schema.json
{
	"title": "JSON schema for rsconfig.json file.",
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties": true,
	"required": ["routes"],
	"properties": {
		"routes": {
			"type": "array",
			"title": "Definition of routes.",
			"items": {
				"type": "object",
				"required": ["route", "title"],
				"properties": {
					"route": {
						"type": "string",
						"title": "Route for the browser."
					},
					"component": {
						"type": "string",
						"title": "Relative path to the component in app directory."
					},
					"title": {
						"type": "string",
						"title": "Title for the <title> tag in HTML. If the text starts with the ':' the title is searched in the dictionaries without the first character."
					},
					"requireAuth": {
						"type": "boolean",
						"title": "Indicates if the route requires authorization.",
						"default": false
					},
					"method": {
						"type": "string",
						"enum": ["GET", "POST", "PUT", "DELETE"],
						"title": "HTTP method.",
						"default": "GET"
					},
					"layout": {
						"type": "string",
						"title": "Relative path to the custom layout file from the application root.",
						"default": null
					},
					"callback": {
						"type": "string",
						"title": "Relative path to the file containing callback function for the route."
					}
				}
			}
		},
		"components": {
			"type": "array",
			"title": "Definition of components rendered in server DOM.",
			"items": {
				"type": "object",
				"required": ["id", "component"],
				"properties": {
					"id": {
						"type": "string",
						"title": "ID of the HTML element in server DOM."
					},
					"component": {
						"type": "string",
						"title": "Relative path to the component from app directory."
					},
					"auto": {
						"type": "boolean",
						"title": "Indicates if the component's wrapper should be automatically rendered in the layout's body.",
						"default": false
					}
				}
			}
		},
		"socketClassDir": {
			"type": "string",
			"title": "Relative to the directory with socket classes from application root.",
			"default": null
		},
		"errorPage": {
			"type": "string",
			"title": "Relative path to the Error page from the app directory.",
			"default": null
		},
		"componentProvider": {
			"type": "string",
			"title": "Relative path to the Component Provider from the app directory.",
			"default": null
		},
		"componentErrorHandler": {
			"type": "string",
			"title": "Relative path to the Component Error Handler from the app directory.",
			"default": null
		},
		"port": {
			"type": ["integer", "string"],
			"title": "Port on which the app listens.",
			"default": 8080
		},
		"staticDir": {
			"type": "string",
			"title": "Relative path to the static directory for the express app from the application root.",
			"default": "./public"
		},
		"dev": {
			"type": "boolean",
			"title": "Indicates if the application is in DEV mode.",
			"default": false
		},
		"jsDir": {
			"type": "string",
			"title": "Name of the directory where the javascript is located in the staticDir",
			"default": "js"
		},
		"cssDir": {
			"type": "string",
			"title": "Name of the directory where the css is located in the staticDir",
			"default": "css"
		},
		"filename": {
			"type": "string",
			"title": "Name of the bundle file",
			"default": "bundle.js"
		},
		"appDir": {
			"type": "string",
			"title": "Relative path to the app directory from the application root.",
			"default": "./app"
		},
		"entryFile": {
			"type": "string",
			"title": "Relative path to the entry file from the app directory.",
			"default": null
		},
		"layoutComponent": {
			"type": "string",
			"title": "Relative path to the Layout component file from the application root.",
			"default": null
		},
		"cookies": {
			"type": "object",
			"title": "Configuration for cookies.",
			"properties": {
				"secret": {
					"type": "string",
					"title": "Secret which is used to sign cookies",
					"default": null
				},
				"secure": {
					"type": "boolean",
					"title": "Secure flat for the cookies",
					"default": true
				},
				"httpOnly": {
					"type": "boolean",
					"title": "HttpOnly flag for the cookies",
					"default": true
				},
				"domain": {
					"type": "string",
					"title": "Domain flag for the cookies",
					"default": null
				},
				"sameSite": {
					"type": "string",
					"title": "SameSite flag for the cookies",
					"default": null
				}
			}
		},
		"scripts": {
			"type": "array",
			"title": "List of scripts loaded in the server HTML.",
			"items": {
				"type": "string"
			}
		},
		"styles": {
			"type": "array",
			"title": "List of styles loaded in the server HTML.",
			"items": {
				"type": "string"
			}
		},
		"mergeStyles": {
			"type": "array",
			"title": "List of styles to merge to rs-app.css.",
			"items": {
				"type": "string",
				"title": "Relative path to the style from the application root."
			}
		},
		"session": {
			"type": "string",
			"title": "Relative path to the Session class file from the application root.",
			"default": null
		},
		"socketMessageMaxSize": {
			"type": "integer",
			"title": "Maximal size of one socket message.",
			"default": 104857600
		},
		"auth": {
			"type": "string",
			"title": "Relative path to the file with exported auth function.",
			"default": null
		},
		"errorHandler": {
			"type": "string",
			"title": "Relative path to the file with exported error handler function.",
			"default": null
		},
		"bundlePathRelative": {
			"type": "boolean",
			"title": "Indicates if the bundle is loaded relatively in the server HTML.",
			"default": false
		},
		"onWebpackProgress": {
			"type": "string",
			"title": "Relative path to the file with exported webpack progress function.",
			"default": null
		},
		"webpack": {
			"type": ["string", "object"],
			"title": "Custom webpack config. It can be object or relative path to the webpack config file."
		},
		"socketIO": {
			"type": "object",
			"title": "Custom socketIO config."
		},
		"autoprefixer": {
			"type": "object",
			"title": "Custom autoprefixer config."
		},
		"babelTranspileModules": {
			"type": "array",
			"title": "List of modules to add to the babel-loader.",
			"items": {
				"type": "string"
			}
		},
		"createMissingComponents": {
			"type": "boolean",
			"title": "Indicates if registered components should be created if missing.",
			"default": false
		},
		"generatedComponentsExtension": {
			"type": "string",
			"title": "Extension of the generated components.",
			"enum": ["js", "jsx", "ts", "tsx"],
			"default": "tsx"
		},
		"sourceStylesDir": {
			"type": "string",
			"title": "Relative path to the directory containing source styles that are merged to app styles.",
			"default": null
		},
		"connectSocketAutomatically": {
			"type": "boolean",
			"title": "Indicates if the socket should be connected automatically after the bundle load.",
			"default": true
		},
		"locale": {
			"type": "object",
			"title": "Configuration for locale.",
			"properties": {
				"default": {
					"type": "string",
					"title": "Default locale of the website. This locale will be used in default.json.",
					"default": "en-US"
				},
				"accepted": {
					"type": "array",
					"title": "List of accepted locales.",
					"items": {
						"type": "string"
					},
					"default": []
				}
			}
		},
		"plugins": {
			"type": "array",
			"title": "List of plugins.",
			"items": {
				"anyOf": [
					{
						"type": "string",
						"title": "Path to the module or its name to require from node_modules."
					},
					{
						"type": "array",
						"title": "Specification of plugin with options",
						"minItems": 1,
						"maxItems": 2,
						"items": [
							{
								"type": "string",
								"title": "Path to the module or its name to require from node_modules."
							},
							{
								"type": "object",
								"title": "Options of the plugin."
							}
						]
					}
				]
			},
			"default": []
		},
		"logging": {
			"type": "boolean",
			"title": "Indicates if the server logs to the console.",
			"default": true
		},
		"error": {
			"type": "object",
			"title": "Configuration for error handling.",
			"properties": {
				"handler": {
					"type": "string",
					"title": "Relative path to the file with exported error handler function.",
					"default": null
				},
				"page": {
					"type": "string",
					"title": "Relative path to the error page from the app directory.",
					"default": null
				},
				"layout": {
					"type": "string",
					"title": "Relative path to the layout file.",
					"default": null
				}
			}
		},
		"bundleAfterServerStart": {
			"type": "boolean",
			"title": "Indicates if the server should be started before the webpack bundle. In that case bundling info page is rendered.",
			"default": false
		},
		"tsCompilerOptions": {
			"type": "object",
			"title": "Custom TypeScript compiler options.",
			"default": {}
		},
		"envVars": {
			"type": "object",
			"title": "Environment variables.",
			"default": {}
		}
	}
}

=== jdolinski1/reacting-squirrel-fix/__tests__app__/dev/rsconfig.json
{
	"$schema": "../../schemas/rsconfig.schema.json",
	"routes": [
		{
			"route": "/",
			"component": "home",
			"title": ":home"
		},
		{
			"route": "/about",
			"component": "about",
			"title": "About"
		},
		{
			"route": "/socket",
			"component": "socket",
			"title": "Socket"
		},
		{
			"route": "/decorators",
			"component": "decorators",
			"title": "Decorators"
		},
		{
			"route": "/models",
			"component": "models",
			"title": "Models"
		},
		{
			"route": "/layout-test",
			"component": "home",
			"title": "Layout test",
			"layout": "__tests__app__/dev/dist/layout"
		},
		{
			"route": "/generated-page",
			"component": "generated",
			"title": "Generated page"
		},
		{
			"route": "/ui",
			"component": "ui",
			"title": "UI"
		},
		{
			"route": "/no-component",
			"title": "No component"
		},
		{
			"route": "/large-data",
			"component": "large-data",
			"title": "Large data"
		},
		{
			"route": "/callback",
			"title": "Callback",
			"callback": "__tests__app__/dev/dist/callbacks/callback"
		}
	],
	"components": [
		{
			"id": "test",
			"component": "test"
		},
		{
			"id": "socket-status",
			"component": "socket-status"
		},
		{
			"id": "generated",
			"component": "generated-component",
			"auto": true
		}
	],
	"socketClassDir": "__tests__app__/dev/dist/socket",
	"error": {
		"page": "page.error",
		"layout": "./__tests__app__/dev/dist/layout.error"
	},
	"errorHandler": "./__tests__app__/dev/dist/error-handler",
	"createMissingComponents": true,
	"mergeStyles": ["./node_modules/bootstrap/dist/css/bootstrap.css"],
	"layoutComponent": "./__tests__app__/dev/dist/layout",
	"sourceStylesDir": "./__tests__app__/dev/src/styles",
	"plugins": [
		[
			"./__tests__app__/dev/dist/plugin",
			{
				"test": "test"
			}
		],
		"test"
	],
	"port": "$env:PORT",
	"cookies": {
		"secure": true,
		"sameSite": "None"
	}
}
